name: noteapp
description: "Test Case"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  dio: ^5.9.0
  retrofit: ^4.6.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1
  envied: ^1.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_crashlytics: ^4.0.8
  firebase_analytics: ^11.3.3
  tutorial_coach_mark: ^1.3.1
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.1
  sqflite: ^2.3.3
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.11.0
  flutter_native_splash: ^2.4.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  very_good_analysis: ^8.0.0


flutter:


  uses-material-design: true


  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/core/gen

