// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5DsJsFHpC8UpCZuJLHCSJWF_H6t3GvE',
    appId: '1:640942233522:web:f16d3eb005d2095e6fb6ab',
    messagingSenderId: '640942233522',
    projectId: 'fastapi-testcase',
    authDomain: 'fastapi-testcase.firebaseapp.com',
    storageBucket: 'fastapi-testcase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0sxIO-VNhQcTX7cgt4rw5o6p-13XYGk',
    appId: '1:640942233522:android:f3f26cf9ba9933996fb6ab',
    messagingSenderId: '640942233522',
    projectId: 'fastapi-testcase',
    storageBucket: 'fastapi-testcase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSu4XP7G-4Go8BCBW_v66N7Qm8BH8tqyQ',
    appId: '1:640942233522:ios:351a0e76d6459c906fb6ab',
    messagingSenderId: '640942233522',
    projectId: 'fastapi-testcase',
    storageBucket: 'fastapi-testcase.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSu4XP7G-4Go8BCBW_v66N7Qm8BH8tqyQ',
    appId: '1:640942233522:ios:351a0e76d6459c906fb6ab',
    messagingSenderId: '640942233522',
    projectId: 'fastapi-testcase',
    storageBucket: 'fastapi-testcase.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5DsJsFHpC8UpCZuJLHCSJWF_H6t3GvE',
    appId: '1:640942233522:web:240a2f6762c4c7246fb6ab',
    messagingSenderId: '640942233522',
    projectId: 'fastapi-testcase',
    authDomain: 'fastapi-testcase.firebaseapp.com',
    storageBucket: 'fastapi-testcase.firebasestorage.app',
  );
}
