import 'package:flutter/material.dart';

@immutable
final class AppTheme {
  const AppTheme._();

  /// [1] [Açık Tema]
  static final lightTheme = ThemeData(
    colorScheme: lightScheme,
  );

  /// [2] [Koyu Tema]
  static final darkTheme = ThemeData(
    colorScheme: darkScheme,
  );

  /// Material Design 3 Konseptine Uygun Özel Color Scheme Oluşturduk
  static ColorScheme get lightScheme => const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff006a60),
      surfaceTint: Color(0xff006a60),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff9ef2e4),
      onPrimaryContainer: Color(0xff005048),
      secondary: Color(0xff4a635f),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffcce8e2),
      onSecondaryContainer: Color(0xff334b47),
      tertiary: Color(0xff466179),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffcce5ff),
      onTertiaryContainer: Color(0xff2d4961),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfff4fbf8),
      onSurface: Color(0xff161d1c),
      onSurfaceVariant: Color(0xff3f4947),
      outline: Color(0xff6f7977),
      outlineVariant: Color(0xffbec9c6),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2b3230),
      inversePrimary: Color(0xff82d5c9),
      primaryFixed: Color(0xff9ef2e4),
      onPrimaryFixed: Color(0xff00201c),
      primaryFixedDim: Color(0xff82d5c9),
      onPrimaryFixedVariant: Color(0xff005048),
      secondaryFixed: Color(0xffcce8e2),
      onSecondaryFixed: Color(0xff05201c),
      secondaryFixedDim: Color(0xffb1ccc6),
      onSecondaryFixedVariant: Color(0xff334b47),
      tertiaryFixed: Color(0xffcce5ff),
      onTertiaryFixed: Color(0xff001d31),
      tertiaryFixedDim: Color(0xffadcae6),
      onTertiaryFixedVariant: Color(0xff2d4961),
      surfaceDim: Color(0xffd5dbd9),
      surfaceBright: Color(0xfff4fbf8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xffeff5f2),
      surfaceContainer: Color(0xffe9efed),
      surfaceContainerHigh: Color(0xffe3eae7),
      surfaceContainerHighest: Color(0xffdde4e1),
      );

  /// Material Design 3 Konseptine Uygun Özel Color Scheme Oluşturduk
  static ColorScheme get darkScheme => const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffaffff2),
      surfaceTint: Color(0xff82d5c9),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xff7ed1c5),
      onPrimaryContainer: Color(0xff000e0c),
      secondary: Color(0xffdaf6f0),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffadc8c3),
      onSecondaryContainer: Color(0xff000e0c),
      tertiary: Color(0xffe6f1ff),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffa9c6e2),
      onTertiaryContainer: Color(0xff000c18),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea4),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff0e1513),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      outline: Color(0xffe8f2ef),
      outlineVariant: Color(0xffbac5c2),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffdde4e1),
      inversePrimary: Color(0xff00514a),
      primaryFixed: Color(0xff9ef2e4),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xff82d5c9),
      onPrimaryFixedVariant: Color(0xff001512),
      secondaryFixed: Color(0xffcce8e2),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffb1ccc6),
      onSecondaryFixedVariant: Color(0xff001512),
      tertiaryFixed: Color(0xffcce5ff),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffadcae6),
      onTertiaryFixedVariant: Color(0xff001321),
      surfaceDim: Color(0xff0e1513),
      surfaceBright: Color(0xff4b5150),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff1a2120),
      surfaceContainer: Color(0xff2b3230),
      surfaceContainerHigh: Color(0xff363d3b),
      surfaceContainerHighest: Color(0xff414846),
      );
}
